### ISSUE TITLE
Баг с Раздатчиком тофу

### ISSUE THREAD

**Issue by Timur13240** [MAGNAT2645/Earthbound-RUS#6]
Получив _Раздатчик тофу_, я сразу попробывал его использовать вне боя.
Игра должны была сказать - "Несс не смог использовать _Раздатч. тофу_.", 
но почему-то игра говорит - "Несс не смог использовать Слом. тромбон."

https://user-images.githubusercontent.com/46261539/177016997-1fb12a4e-86b0-4d1f-8d4c-b9ded5a0289d.mp4

**Comment by MAGNAT2645** [comment]
Исправлено. Спасибо за находку.
